# Generated by Django 6.0 on 2025-12-23 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_companyholiday_companypolicy'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllowedIPRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Descriptive name for this IP range (e.g., 'Office WiFi')", max_length=100)),
                ('ip_range', models.CharField(help_text='IP range in CIDR notation (e.g., 192.168.1.0/24) or individual IP', max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this IP range is currently active')),
                ('description', models.TextField(blank=True, help_text='Optional description of where this IP range is used')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Allowed IP Range',
                'verbose_name_plural': 'Allowed IP Ranges',
                'ordering': ['-created_at'],
            },
        ),
    ]
